[package]
name = "laz2dem"
version = "0.1.0"
edition = "2024"

[dependencies]
dem-common = { path = "../dem-common" }
image = { version = "0.25.6", default-features = false, features = [
    "jpeg",
    "png",
] }
las = { version = "0.9.5", features = ["laz-parallel"] }
proj = "0.30.0"
rayon = "1.10.0"
rusqlite = "0.34.0"
spade = "2.13.1"
tilemath = "0.3.0"
clap = { version = "4.5.38", features = ["derive"] }
itertools = "0.14.0"
ndarray = "0.16.1"
lru = "0.14.0"

[profile.release]
panic = "abort"
